### PR TITLE
Ma nouvelle branche3

### PR DESCRIPTION
**Pull request by ghost**
Hello,
I am attaching you to the third test case with the remarks I have seen (report2.pdf)
@pradal 
@artzet-s

### CODE REVIEW

**Comment by julien-diener** [comment]
Sorry to intervene, I still receive github mail and I took a look this morning

It seems you copied the whole code in the example folder. Was it on purpose ?

**Comment by brhell** [comment]
No, because I wanted to copy what I tested.
Can you tell me how?

**Comment by brhell** [comment]
No, because I wanted to copy what I tested.
Can you tell me how?
@julien-diener

**Comment by julien-diener** [comment]
Sorry I didn't answer in time.

I meant that it isn't usually a good idea to copy code (duplication is "evil"). I understand that you wanted to keep of copy of the code that has been tested, so that it won't be changed by later commit. I understand it but I think it would be good to think of a better method for next time.

To propose an idea, maybe you could simply save the commit used when executing the test (eg. as a comment in the main doc or executable). It should be enough to be able to re-execute the test later on the exact same code, and you will also be able to easily execute the test on new version of the code, for comparison.

**Comment by pradal** [comment]
I completly agree with Julin. You do not have to copy anything. If you want to test, you just create a branch. A branch in git is a copy. But a smart copy. Only the diff are saved.
 And the way to take nito account your modifications is only to install (or use the mode develop) you branch.

Something like:
python setup.py develop 
in a conda environment.

**Pull request closed without merging**
